### ISSUE TITLE
options files

### ISSUE THREAD

**Issue by tmbdev** [tiangolo/typer#49]
I want to be able to load options defaults from an options file (e.g., in YAML or JSON) to be able to define default options for commands.

Add a clear and concise description of what you want to happen.

```Python
    app = typer.Typer()
    app.load_options("options.yaml")

    @app.command()
    def command1(option1:int=0, option2:str=""):
        ...

    @app.command()
    def command2(something:str, count:int=0):
        ...
 
    if __name__ == "__main__":
        app()
```

The `options.yaml` file would look something like this:

```YAML
    command1:
        option1: 1234
    command2:
        something: value
        count: 17
```

The suggested order of precedence is:

  1. command line options
  2. environment variables
  3. loaded options
  4. defaults from function signature
